#!/bin/bash
#Script for disabling cumbox rule on rpi so you can manually run checkra1n
echo disabling cumbox script \(don\'t forget to renable\)...
cd /etc/udev/rules.d/
sudo mv 01-cumbox.rules 01-cumbox.rules.bak
echo reloading udev rules...
sudo udevadm control --reload-rules && sudo udevadm trigger
echo since you have cumbox installed, you can find check rain at \"/opt/cumbox/checkra1n\"...